### ISSUE TITLE
Bug during ePUB import: CSS code is included in paragraph

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#975]
When importing the Hindi storybook ePUB from https://storyweaver.org.in/stories/10145-ek-sau-saintisvan-paer, the CSS code is included as its own paragraph:
```css
@page { margin: 0.79in } p { margin-bottom: 0.1in; direction: ltr; color: #000000; line-height: 120%; orphans: 2; widows: 2 } p.western { font-family: "Calibri", sans-serif; font-size: 11pt; so-language: en-GB } p.cjk { font-family: "Calibri", sans-serif; font-size: 11pt } p.ctl { font-family: "Mangal", serif; font-size: 11pt; so-language: ar-SA }
```

See http://hin.elimu.ai/content/storybook/edit/53

Looks for ways to exclude CSS code during ePUB import.
